/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private String display = "";
    private char lastChar = ' ';
    
    public MainFrame() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        digitDisplayPanel = new javax.swing.JPanel();
        digitDisplayText = new javax.swing.JTextField();
        numPadPanel = new javax.swing.JPanel();
        ceBtn = new javax.swing.JButton();
        openingBtn = new javax.swing.JButton();
        closingBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        exponentBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        pointBtn = new javax.swing.JButton();
        operationsPanel = new javax.swing.JPanel();
        divideBtn = new javax.swing.JButton();
        multiplyBtn = new javax.swing.JButton();
        subtractBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        equalsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(51, 110, 123));

        digitDisplayPanel.setBackground(new java.awt.Color(51, 110, 123));

        digitDisplayText.setBackground(new java.awt.Color(149, 165, 166));
        digitDisplayText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout digitDisplayPanelLayout = new javax.swing.GroupLayout(digitDisplayPanel);
        digitDisplayPanel.setLayout(digitDisplayPanelLayout);
        digitDisplayPanelLayout.setHorizontalGroup(
            digitDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digitDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(digitDisplayText)
                .addContainerGap())
        );
        digitDisplayPanelLayout.setVerticalGroup(
            digitDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digitDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(digitDisplayText, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        numPadPanel.setBackground(new java.awt.Color(51, 110, 123));
        numPadPanel.setLayout(new java.awt.GridLayout(0, 3, 6, 6));

        ceBtn.setBackground(new java.awt.Color(1, 50, 67));
        ceBtn.setText("CE");
        ceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(ceBtn);

        openingBtn.setBackground(new java.awt.Color(1, 50, 67));
        openingBtn.setText("(");
        openingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openingBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(openingBtn);

        closingBtn.setBackground(new java.awt.Color(1, 50, 67));
        closingBtn.setText(")");
        closingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closingBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(closingBtn);

        oneBtn.setBackground(new java.awt.Color(149, 165, 166));
        oneBtn.setText("1");
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(oneBtn);

        twoBtn.setBackground(new java.awt.Color(149, 165, 166));
        twoBtn.setText("2");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(twoBtn);

        threeBtn.setBackground(new java.awt.Color(149, 165, 166));
        threeBtn.setText("3");
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(threeBtn);

        fourBtn.setBackground(new java.awt.Color(149, 165, 166));
        fourBtn.setText("4");
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(fourBtn);

        fiveBtn.setBackground(new java.awt.Color(149, 165, 166));
        fiveBtn.setText("5");
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(fiveBtn);

        sixBtn.setBackground(new java.awt.Color(149, 165, 166));
        sixBtn.setText("6");
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(sixBtn);

        sevenBtn.setBackground(new java.awt.Color(149, 165, 166));
        sevenBtn.setText("7");
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(sevenBtn);

        eightBtn.setBackground(new java.awt.Color(149, 165, 166));
        eightBtn.setText("8");
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(eightBtn);

        nineBtn.setBackground(new java.awt.Color(149, 165, 166));
        nineBtn.setText("9");
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(nineBtn);

        exponentBtn.setBackground(new java.awt.Color(1, 50, 67));
        exponentBtn.setText("^");
        exponentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exponentBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(exponentBtn);

        zeroBtn.setBackground(new java.awt.Color(149, 165, 166));
        zeroBtn.setText("0");
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(zeroBtn);

        pointBtn.setBackground(new java.awt.Color(1, 50, 67));
        pointBtn.setText(".");
        pointBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointBtnActionPerformed(evt);
            }
        });
        numPadPanel.add(pointBtn);

        operationsPanel.setBackground(new java.awt.Color(51, 110, 123));
        operationsPanel.setPreferredSize(new java.awt.Dimension(80, 100));
        operationsPanel.setLayout(new java.awt.GridLayout(0, 1, 6, 6));

        divideBtn.setBackground(new java.awt.Color(1, 50, 67));
        divideBtn.setText("/");
        divideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtnActionPerformed(evt);
            }
        });
        operationsPanel.add(divideBtn);

        multiplyBtn.setBackground(new java.awt.Color(1, 50, 67));
        multiplyBtn.setText("*");
        multiplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBtnActionPerformed(evt);
            }
        });
        operationsPanel.add(multiplyBtn);

        subtractBtn.setBackground(new java.awt.Color(1, 50, 67));
        subtractBtn.setText("-");
        subtractBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractBtnActionPerformed(evt);
            }
        });
        operationsPanel.add(subtractBtn);

        addBtn.setBackground(new java.awt.Color(1, 50, 67));
        addBtn.setText("+");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        operationsPanel.add(addBtn);

        equalsBtn.setBackground(new java.awt.Color(1, 50, 67));
        equalsBtn.setText("=");
        equalsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsBtnActionPerformed(evt);
            }
        });
        operationsPanel.add(equalsBtn);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(digitDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numPadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(operationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(digitDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numPadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(operationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceBtnActionPerformed
        digitDisplayText.setText("");
    }//GEN-LAST:event_ceBtnActionPerformed

    private void openingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openingBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "(");
    }//GEN-LAST:event_openingBtnActionPerformed

    private void closingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closingBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + ")");
    }//GEN-LAST:event_closingBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "1");
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "2");
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "3");
    }//GEN-LAST:event_threeBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "4");
    }//GEN-LAST:event_fourBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "5");
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "6");
    }//GEN-LAST:event_sixBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "7");
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "8");
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "9");
    }//GEN-LAST:event_nineBtnActionPerformed

    private void exponentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exponentBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + " ^ ");
    }//GEN-LAST:event_exponentBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + "0");
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void pointBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointBtnActionPerformed
        display = digitDisplayText.getText();
        digitDisplayText.setText(display + ".");
    }//GEN-LAST:event_pointBtnActionPerformed

    private void divideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtnActionPerformed
        display = digitDisplayText.getText();
        
        if (!display.isEmpty()) {
            digitDisplayText.setText(display + " / ");
        }
    }//GEN-LAST:event_divideBtnActionPerformed

    private void multiplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBtnActionPerformed
        display = digitDisplayText.getText();
        
        if (!display.isEmpty()) {
            digitDisplayText.setText(display + " * ");
        }
    }//GEN-LAST:event_multiplyBtnActionPerformed

    private void subtractBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractBtnActionPerformed
        display = digitDisplayText.getText();
        
        // Gets the last character of display if it's not empty
        if (!display.isEmpty()) {
            String noSpace = display.replaceAll("\\s", "");
            lastChar = noSpace.charAt(noSpace.length() - 1);
        }
        
        // Uses negative sign if display is empty or last character is an operator
        if (display.isEmpty() || lastChar == '^' || lastChar == '*' || lastChar == '/' || lastChar == '+' || lastChar == '-' || lastChar == '(') {
            digitDisplayText.setText(display + "-");
        }
        
        else {
            digitDisplayText.setText(display + " - ");
        }
    }//GEN-LAST:event_subtractBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        display = digitDisplayText.getText();
        
        if (!display.isEmpty()) {
            digitDisplayText.setText(display + " + ");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void equalsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsBtnActionPerformed
        display = digitDisplayText.getText();
        
        if (display.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No expression detected.");
            return;
        }
        
        // Converts infix string to postfix and prefix before evaluating 
        String postfix = PostfixString.postfix(this.display);
        String prefix = PrefixString.prefix(this.display);
        String answer = String.valueOf(EvaluateString.evaluate(postfix));
        digitDisplayText.setText(answer);
        
        ResultFrame result = new ResultFrame(answer, postfix, prefix);
        result.setVisible(true);
    }//GEN-LAST:event_equalsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton ceBtn;
    private javax.swing.JButton closingBtn;
    private javax.swing.JPanel digitDisplayPanel;
    private javax.swing.JTextField digitDisplayText;
    private javax.swing.JButton divideBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton equalsBtn;
    private javax.swing.JButton exponentBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton multiplyBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JPanel numPadPanel;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton openingBtn;
    private javax.swing.JPanel operationsPanel;
    private javax.swing.JButton pointBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton subtractBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
